version: "2.0"
services:
  # 第1个容器
  jd1:
    image: evinedeng/jd  # 如果要从gitee更新脚本，则为：evinedeng/jd:gitee
    container_name: jd1
    restart: always
    tty: true
    network_mode: "bridge"
    hostname: jd1
    volumes:
      - ./jd1/config.sh:/jd/config.sh        # 请在部署容器前先把./jd1/config.sh这个文件准备好，下同
      - ./jd1/crontab.list:/jd/crontab.list  # 请在部署容器前先把./jd1/crontab.list这个文件准备好，下同
      - ./jd1/log:/jd/log

  # 第2个容器
  jd2:
    image: evinedeng/jd # 如果要从gitee更新脚本，则为：evinedeng/jd:gitee
    container_name: jd2
    restart: always
    tty: true
    network_mode: "bridge"
    hostname: jd2
    volumes:
      - ./jd2/config.sh:/jd/config.sh
      - ./jd2/crontab.list:/jd/crontab.list
      - ./jd2/log:/jd/log

  # 第3个容器，以此类推
  jd3:
    image: evinedeng/jd # 如果要从gitee更新脚本，则为：evinedeng/jd:gitee
    container_name: jd3
    restart: always
    tty: true
    network_mode: "bridge"
    hostname: jd3
    volumes:
      - ./jd3/config.sh:/jd/config.sh
      - ./jd3/crontab.list:/jd/crontab.list
      - ./jd3/log:/jd/log